### ISSUE TITLE
自オブジェクトを返すメソッドの戻り値の型について

### ISSUE THREAD

**Issue by kent013** [blastengineMania/blastengine-php#1]
例えば`Base.php`で
```
function from(string $email, ?string $name = null): Base
```
と定義されていますが、Transactionで
```
$transaction = new Transaction();
$transaction->from('hoge@example.test', 'Test Taro')->to('moge@example.test');
```
とすると、fromの戻り値が`Base`クラスなので
```
Call to an undefined method Blastengine\Base::to().
```
となります。`static`でアノテーションするようにしていただけないでしょうか。

可能であればphpstan level=maxでエラーが出ないようになるとベストです。

**Comment by goofmint** [comment]
@kent013 フィードバックありがとうございます！こちら対応しました

PHPStanは、とりあえずレベル7までサポートしました。maxはレベル9だと思いますが、これはまだまだ先が長いです

blastengine/blastengine - Packagist https://packagist.org/packages/blastengine/blastengine
